/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CalendarPicker {
    'multipleDays': boolean;
  }
}

declare global {


  interface HTMLCalendarPickerElement extends Components.CalendarPicker, HTMLStencilElement {}
  var HTMLCalendarPickerElement: {
    prototype: HTMLCalendarPickerElement;
    new (): HTMLCalendarPickerElement;
  };
  interface HTMLElementTagNameMap {
    'calendar-picker': HTMLCalendarPickerElement;
  }
}

declare namespace LocalJSX {
  interface CalendarPicker extends JSXBase.HTMLAttributes<HTMLCalendarPickerElement> {
    'multipleDays'?: boolean;
    'onSelectedDaysUpate'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'calendar-picker': CalendarPicker;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


